global_costmap:
    static_map: true
    global_frame: map
    rolling_window: false
    track_unknown_space: true
    update_frequency: 5.0
    publish_frequency: 5.0
    plugins:
        - {name: static,                  type: "costmap_2d::StaticLayer"}
        - {name: obstacles_costmap2d,       type: "costmap_2d::ObstacleLayer"}
        - {name: inflation,               type: "costmap_2d::InflationLayer"}
