global_costmap:
    global_frame: map
    rolling_window: false
    track_unknown_space: true

    plugins:
        - {name: localization_map, type: "costmap_2d::StaticLayer"}
        - {name: preferences_map, type: "costmap_2d::StaticLayer"}
        - {name: obstacles_costmap2d, type: "costmap_2d::ObstacleLayer"}
        - {name: inflation, type: "costmap_2d::InflationLayer"}

    # using the map topic means that amcl will use it
    # for localization. This map should be the raw output
    # of running gmapping
    localization_map:
      map_topic: "/map"
      first_map_only: true

    preferences_map:
      map_topic: "/preferences_map"
      first_map_only: true

    # having high inflation with high cost scaling is better
    # then low inflation and low cost scaling because then it
    # the robot drives further from things normally unless it needs
    # to go closer
    inflation:
      inflation_radius: 1.0
      cost_scaling_factor: 15

