# 2D Costmap parameters
# http://www.ros.org/wiki/costmap_2d

### Coordinate frame and tf parameters ###
robot_base_frame:           base_link
transform_tolerance:        0.5

# ---Vector footprint (Meters):---
footprint: [[0.365163875,0.27580937],[0.365163875,-0.27580937],[-0.365163875,-0.27580937],[-0.365163875,0.27580937]]

# The following parameter is overwritten if the "footprint" parameter is set
#robot_radius:               0.325

### Costmap layer definitions ###
#publish_frequency:           1.0
#plugins:                     []

#static:
#  unknown_cost_value:        -1
#  cost_factor:               0.55
#  neutral_cost:              66
#  lethal_cost_threshold:     253
#  map_topic:                 map
#  subscribe_to_updates:      true

obstacles_costmap2d:
  observation_sources: vector_scan
  vector_scan: {
                sensor_frame:            /front_laser_link,
                topic:                   /vector/front_scan,
                data_type:               LaserScan,
                inf_is_valid:            true,
                marking:                 true,
                clearing:                true,
                obstacle_range:          2.75,
                raytrace_range:          3.0}

inflation:
  inflation_radius:           0.75 #default 0.5
  cost_scaling_factor:        10.0 #default 10.0

